### ISSUE TITLE
Error when analyzing Java 8 class files

### ISSUE THREAD

**Issue by veita** [jesperpedersen/tattletale#30]
java.io.IOException: invalid constant type: 18
        at javassist.bytecode.ConstPool.readOne(ConstPool.java:1090)
        at javassist.bytecode.ConstPool.read(ConstPool.java:1033)
        at javassist.bytecode.ConstPool.<init>(ConstPool.java:149)
        at javassist.bytecode.ClassFile.read(ClassFile.java:764)
        at javassist.bytecode.ClassFile.<init>(ClassFile.java:108)
        at javassist.CtClassType.<init>(CtClassType.java:94)
        at javassist.ClassPool.makeClass(ClassPool.java:717)
        at javassist.ClassPool.makeClass(ClassPool.java:695)
        at org.jboss.tattletale.analyzers.AbstractScanner.scanClasses(AbstractScanner.java:179)
        at org.jboss.tattletale.analyzers.JarScanner.scan(JarScanner.java:106)
        at org.jboss.tattletale.Main.execute(Main.java:612)
        at org.jboss.tattletale.Main.main(Main.java:1099)

This can be fixed by building Tattletale with `<property name="version.javassist" value="3.19.0-GA"/>` in the build.xml.

**Comment by jforge** [comment]
Just saw your issue after getting the same error.
I've created a pull requests with an update to javassist 3.20.0-GA.
https://github.com/jesperpedersen/tattletale/pull/33

I hope there will be an official version in the near future.

**Comment by bpbhat77** [comment]
added JAVA 8 support. checkout here https://github.com/bpbhat77/tattletale
