### ISSUE TITLE
Bug: ant:tattlereport throwing ClassCastException

### ISSUE THREAD

**Issue by terry-citrix** [jesperpedersen/tattletale#35]
**Expected**
That TattleReport run without producing errors, or if an error does occur that it explains what the error is.  No unhandled exceptions are expected -- TattleReport is expected to gracefully handle malformed input and similar.

**Actual**
The following stack trace is shown in our build system:

[ant:tattletaleReport] java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
[ant:tattletaleReport]  at org.jboss.tattletale.analyzers.AbstractScanner.scanClasses(AbstractScanner.java:190)
[ant:tattletaleReport]  at org.jboss.tattletale.analyzers.JarScanner.scan(JarScanner.java:106)
[ant:tattletaleReport]  at org.jboss.tattletale.Main.execute(Main.java:612)
[ant:tattletaleReport]  at org.jboss.tattletale.ant.ReportTask.execute(ReportTask.java:310)
[ant:tattletaleReport]  at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[ant:tattletaleReport]  at sun.reflect.GeneratedMethodAccessor325.invoke(Unknown Source)
[ant:tattletaleReport]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:tattletaleReport]  at java.lang.reflect.Method.invoke(Method.java:498)
[ant:tattletaleReport]  at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
... snip ...

**Repro**
* It's reproducible every time in my build environment, but I have not yet isolated what is different about my build system.  See the notes below though.

**Notes**
Looking at the code we see the following: https://github.com/jesperpedersen/tattletale/blob/master/src/main/java/org/jboss/tattletale/analyzers/AbstractScanner.java#L190

      Long serialVersionUID = null;
      try
      {
         CtField field = ctClz.getField("serialVersionUID");
         serialVersionUID = (Long) field.getConstantValue();
      }
      catch (NotFoundException nfe)
      {
         // Ignore - not serializable
      }

Therefore it seems likely that the serialVersionUID's value is an Integer, and hence why it's having trouble casting this to a Long.

**Comment by twogee** [comment]
According to [specification](https://docs.oracle.com/javase/8/docs/platform/serialization/spec/class.html) serialVersionUID must be final, static and long. How would you suggest dealing with a class which is non-conformant? Would rethrowing CCE with the name of the offending class added to the message do?
